col = engineLoadCOL ( "TougeOkaru/okaru.col" )
engineReplaceCOL ( col, 1821 )
txd = engineLoadTXD ( "TougeOkaru/okaru.txd" )
engineImportTXD ( txd, 1821 )
dff = engineLoadDFF ( "TougeOkaru/okaru.dff" )
engineReplaceModel ( dff, 1821 )
engineSetModelLODDistance(1821, 2000)

col2 = engineLoadCOL ( "TougeOkaru/okaru1.col" )
engineReplaceCOL ( col2, 2387 )
txd2 = engineLoadTXD ( "TougeOkaru/okaru.txd" )
engineImportTXD ( txd2, 2387 )
dff2 = engineLoadDFF ( "TougeOkaru/okaru1.dff" )
engineReplaceModel ( dff2, 2387 )
engineSetModelLODDistance(2387, 2000)

col3 = engineLoadCOL ( "TougeOkaru/okaru2.col" )
engineReplaceCOL ( col3, 2225 )
txd3 = engineLoadTXD ( "TougeOkaru/okaru.txd" )
engineImportTXD ( txd3, 2225 )
dff3 = engineLoadDFF ( "TougeOkaru/okaru2.dff" )
engineReplaceModel ( dff3, 2225 )
engineSetModelLODDistance(2225, 2000)

col4 = engineLoadCOL ( "TougeOkaru/okaru3.col" )
engineReplaceCOL ( col4, 2227 )
txd4 = engineLoadTXD ( "TougeOkaru/okaru.txd" )
engineImportTXD ( txd4, 2227 )
dff4 = engineLoadDFF ( "TougeOkaru/okaru3.dff" )
engineReplaceModel ( dff4, 2227 )
engineSetModelLODDistance(2227, 2000)

col5 = engineLoadCOL ( "TougeOkaru/okaru4.col" )
engineReplaceCOL ( col5, 1208 )
txd5 = engineLoadTXD ( "TougeOkaru/okaru.txd" )
engineImportTXD ( txd5, 1208 )
dff5 = engineLoadDFF ( "TougeOkaru/okaru4.dff" )
engineReplaceModel ( dff5, 1208 )
engineSetModelLODDistance(1208, 2000)