
txd_Base = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Base, 14420)
dff_Base = engineLoadDFF( "img/Base.dff" )
engineReplaceModel(dff_Base, 14420)
col_Base = engineLoadCOL( "img/Base.col" )
engineReplaceCOL(col_Base, 14420)
engineSetModelLODDistance(14420, 200)

txd_Garage_Furniture = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Garage_Furniture, 14421)
dff_Garage_Furniture = engineLoadDFF( "img/Garage_Furniture.dff" )
engineReplaceModel(dff_Garage_Furniture, 14421)
col_Garage_Furniture = engineLoadCOL( "img/Garage_Furniture.col" )
engineReplaceCOL(col_Garage_Furniture, 14421)
engineSetModelLODDistance(14421, 200)

txd_Glass = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Glass, 14422)
dff_Glass = engineLoadDFF( "img/Glass.dff" )
engineReplaceModel(dff_Glass, 14422)
col_Glass = engineLoadCOL( "img/Glass.col" )
engineReplaceCOL(col_Glass, 14422)
engineSetModelLODDistance(14422, 200)

txd_Lower_Furniture = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Lower_Furniture, 14423)
dff_Lower_Furniture = engineLoadDFF( "img/Lower_Furniture.dff" )
engineReplaceModel(dff_Lower_Furniture, 14423)
col_Lower_Furniture = engineLoadCOL( "img/Lower_Furniture.col" )
engineReplaceCOL(col_Lower_Furniture, 14423)
engineSetModelLODDistance(14423, 200)

txd_Outside_Furniture = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Outside_Furniture, 14424)
dff_Outside_Furniture = engineLoadDFF( "img/Outside_Furniture.dff" )
engineReplaceModel(dff_Outside_Furniture, 14424)
col_Outside_Furniture = engineLoadCOL( "img/Outside_Furniture.col" )
engineReplaceCOL(col_Outside_Furniture, 14424)
engineSetModelLODDistance(14424, 200)

txd_Upper_Furniture = engineLoadTXD( "img/Textures.txd" )
engineImportTXD(txd_Upper_Furniture, 14425)
dff_Upper_Furniture = engineLoadDFF( "img/Upper_Furniture.dff" )
engineReplaceModel(dff_Upper_Furniture, 14425)
col_Upper_Furniture = engineLoadCOL( "img/Upper_Furniture.col" )
engineReplaceCOL(col_Upper_Furniture, 14425)
engineSetModelLODDistance(14425, 200)
