addEventHandler('onClientResourceStart', resourceRoot,
function()
local col1 = engineLoadCOL('img/estadio.col')
engineReplaceCOL(col1, 17511)
local col2 = engineLoadCOL('img/piso.col')
engineReplaceCOL(col2, 17582)
local col3 = engineLoadCOL('img/cancha.col')
engineReplaceCOL(col3, 17953)
local col4 = engineLoadCOL('img/arco.col')
engineReplaceCOL(col4, 2380)
local col5 = engineLoadCOL('img/memorial.col')
engineReplaceCOL(col5, 2473)

local txd1 = engineLoadTXD('img/estadio.txd')
engineImportTXD(txd1, 17511)
local txd2 = engineLoadTXD('img/piso.txd')
engineImportTXD(txd2, 17582)
local txd3 = engineLoadTXD('img/cancha.txd')
engineImportTXD(txd3, 17953)
local txd4 = engineLoadTXD('img/arco.txd')
engineImportTXD(txd4, 2380)
local txd5 = engineLoadTXD('img/memorial.txd')
engineImportTXD(txd5, 2473)

local dff1 = engineLoadDFF('img/estadio.dff')
engineReplaceModel(dff1, 17511)
local dff2 = engineLoadDFF('img/piso.dff')
engineReplaceModel(dff2, 17582)
local dff3 = engineLoadDFF('img/cancha.dff')
engineReplaceModel(dff3, 17953)
local dff4 = engineLoadDFF('img/arco.dff')
engineReplaceModel(dff4, 2380)
local dff5 = engineLoadDFF('img/memorial.dff')
engineReplaceModel(dff5, 2473)

engineSetModelLODDistance(17511, 250)
engineSetModelLODDistance(17582, 250)
engineSetModelLODDistance(17953, 250)
engineSetModelLODDistance(2380, 250)
engineSetModelLODDistance(2473, 250)
end)