
txd = engineLoadTXD ( "img/plaza.txd" )
engineImportTXD ( txd, 6343 )
col = engineLoadCOL ( "img/plaza.col" )
engineReplaceCOL ( col, 6343 )
dff = engineLoadDFF ( "img/plaza.dff" )
engineReplaceModel ( dff, 6343 )
engineSetModelLODDistance(6343, 500)

txd = engineLoadTXD ( "img/estatua.txd" )
engineImportTXD ( txd, 1371 )
col = engineLoadCOL ( "img/estatua.col" )
engineReplaceCOL ( col, 1371 )
dff = engineLoadDFF ( "img/estatua.dff" )
engineReplaceModel ( dff, 1371 )
engineSetModelLODDistance(1371, 500)

txd = engineLoadTXD ( "img/estructura.txd" )
engineImportTXD ( txd, 934 )
col = engineLoadCOL ( "img/estructura.col" )
engineReplaceCOL ( col, 934 )
dff = engineLoadDFF ( "img/estructura.dff" )
engineReplaceModel ( dff, 934 )
engineSetModelLODDistance(934, 500)
