col_torretelefonica = engineLoadCOL ( "TorreTelefonica_objetos-WLC/img/torretelefonica.col" )
engineReplaceCOL ( col_torretelefonica, 3717 )
txd_torretelefonica = engineLoadTXD ( "TorreTelefonica_objetos-WLC/img/torretelefonica.txd" )
engineImportTXD ( txd_torretelefonica, 3717 )
dff_torretelefonica = engineLoadDFF ( "TorreTelefonica_objetos-WLC/img/torretelefonica.dff" )
engineReplaceModel ( dff_torretelefonica, 3717 )
engineSetModelLODDistance(3717, 500)


col_pisotelefonica = engineLoadCOL ( "TorreTelefonica_objetos-WLC/img/pisotelefonica.col" )
engineReplaceCOL ( col_pisotelefonica, 6388 )
txd_pisotelefonica = engineLoadTXD ( "TorreTelefonica_objetos-WLC/img/pisotelefonica.txd" )
engineImportTXD ( txd_pisotelefonica, 6388 )
dff_pisotelefonica = engineLoadDFF ( "TorreTelefonica_objetos-WLC/img/pisotelefonica.dff" )
engineReplaceModel ( dff_pisotelefonica, 6388 )
engineSetModelLODDistance(6388, 500)

col_logomovistar = engineLoadCOL ( "TorreTelefonica_objetos-WLC/img/logomovistar.col" )
engineReplaceCOL ( col_logomovistar, 2741 )
txd_logomovistar = engineLoadTXD ( "TorreTelefonica_objetos-WLC/img/logomovistar.txd" )
engineImportTXD ( txd_logomovistar, 2741 )
dff_logomovistar = engineLoadDFF ( "TorreTelefonica_objetos-WLC/img/logomovistar.dff" )
engineReplaceModel ( dff_logomovistar, 2741 )
engineSetModelLODDistance(2741, 500)