

--ESTACIONES--
--estacion central--
txd = engineLoadTXD ( "img/estacion_central/estacion_central.txd" )
engineImportTXD ( txd, 4853 )
col = engineLoadCOL ( "img/estacion_central/estacion_central.col" )
engineReplaceCOL ( col, 4853 )
dff = engineLoadDFF ( "img/estacion_central/estacion_central.dff" )
engineReplaceModel ( dff, 4853 )
engineSetModelLODDistance(4853, 200)

--vias--
txd = engineLoadTXD ( "img/vias/railtunn1_law2.txd" )
engineImportTXD ( txd, 6292 )
txd = engineLoadTXD ( "img/vias/railway_las.txd" )
engineImportTXD ( txd, 4873 )
txd = engineLoadTXD ( "img/vias/stationtunnel.txd" )
engineImportTXD ( txd, 5772 )
txd = engineLoadTXD ( "img/vias/traintrack_las.txd" )
engineImportTXD ( txd, 4818 )
txd = engineLoadTXD ( "img/vias/traintrack_las2.txd" )
engineImportTXD ( txd, 5117 )
txd = engineLoadTXD ( "img/vias/lasroads_las2.txd" )
engineImportTXD ( txd, 5271 )
txd = engineLoadTXD ( "img/vias/tunnel_law.txd" )
engineImportTXD ( txd, 6248 )
txd = engineLoadTXD ( "img/vias/railwaycuntw.txd" )
engineImportTXD ( txd, 17297 )
txd = engineLoadTXD ( "img/vias/traintunnel2_sfse.txd" )
engineImportTXD ( txd, 10944 )
txd = engineLoadTXD ( "img/vias/traingen_sfse.txd" )
engineImportTXD ( txd, 10931 )
txd = engineLoadTXD ( "img/vias/trainplatform_sfse.txd" )
engineImportTXD ( txd, 11306 )
txd = engineLoadTXD ( "img/vias/traintunnel1_sfse.txd" )
engineImportTXD ( txd, 10927 )
txd = engineLoadTXD ( "img/vias/railbridge_sfse.txd" )
engineImportTXD ( txd, 11256 )
txd = engineLoadTXD ( "img/vias/desn_trainstuff.txd" )
engineImportTXD ( txd, 11464 )
txd = engineLoadTXD ( "img/vias/des_trainstuff.txd" )
engineImportTXD ( txd, 16025 )
txd = engineLoadTXD ( "img/vias/vgwestrailrd.txd" )
engineImportTXD ( txd, 7498 )
txd = engineLoadTXD ( "img/vias/vgnrailroad.txd" )
engineImportTXD ( txd, 6912 )
txd = engineLoadTXD ( "img/vias/vgsrailroad.txd" )
engineImportTXD ( txd, 8625 )
txd = engineLoadTXD ( "img/vias/vgsecoast.txd" )
engineImportTXD ( txd, 8983 )
txd = engineLoadTXD ( "img/vias/ce_traintrack1.txd" )
engineImportTXD ( txd, 12831 )
txd = engineLoadTXD ( "img/vias/ce_traintrack2.txd" )
engineImportTXD ( txd, 13312 )
txd = engineLoadTXD ( "img/vias/railtracklae.txd" )
engineImportTXD ( txd, 5679 )

--OTROS--
txd = engineLoadTXD ( "img/otros/basurero.txd" )
engineImportTXD ( txd, 1333 )
txd = engineLoadTXD ( "img/otros/cartel_metro.txd" )
engineImportTXD ( txd, 1369 )
col = engineLoadCOL ( "img/otros/cartel_metro.col" )
engineReplaceCOL ( col, 1369 )
dff = engineLoadDFF ( "img/otros/cartel_metro.dff" )
engineReplaceModel ( dff, 1369 )
txd = engineLoadTXD ( "img/otros/redbip.txd" )
engineImportTXD ( txd, 962 )
txd = engineLoadTXD ( "img/otros/cajero_bancodechile.txd" )
engineImportTXD ( txd, 2943 )
col = engineLoadCOL ( "img/otros/cajero_bancodechile.col" )
engineReplaceCOL ( col, 2943 )
dff = engineLoadDFF ( "img/otros/cajero_bancodechile.dff" )
engineReplaceModel ( dff, 2943 )
txd = engineLoadTXD ( "img/otros/cajero_bancoestado.txd" )
engineImportTXD ( txd, 2942 )
col = engineLoadCOL ( "img/otros/cajero_bancoestado.col" )
engineReplaceCOL ( col, 2942 )
dff = engineLoadDFF ( "img/otros/cajero_bancoestado.dff" )
engineReplaceModel ( dff, 2942 )
txd = engineLoadTXD ( "img/otros/banca.txd" )
engineImportTXD ( txd, 1256 )
txd = engineLoadTXD ( "img/otros/plataforma_alta.txd" )
engineImportTXD ( txd, 3569 )