
txd_plaza = engineLoadTXD ( "img/plaza.txd" )
engineImportTXD ( txd_plaza, 6343 )
col_plaza = engineLoadCOL ( "img/plaza.col" )
engineReplaceCOL ( col_plaza, 6343 )
dff_plaza = engineLoadDFF ( "img/plaza.dff" )
engineReplaceModel ( dff_plaza, 6343 )
engineSetModelLODDistance(6343, 500)

txd_estatua = engineLoadTXD ( "img/estatua.txd" )
engineImportTXD ( txd_estatua, 1371 )
col_estatua = engineLoadCOL ( "img/estatua.col" )
engineReplaceCOL ( col_estatua, 1371 )
dff_estatua = engineLoadDFF ( "img/estatua.dff" )
engineReplaceModel ( dff_estatua, 1371 )
engineSetModelLODDistance(1371, 500)

txd_estructura = engineLoadTXD ( "img/estructura.txd" )
engineImportTXD ( txd_estructura, 934 )
col_estructura = engineLoadCOL ( "img/estructura.col" )
engineReplaceCOL ( col_estructura, 934 )
dff_estructura = engineLoadDFF ( "img/estructura.dff" )
engineReplaceModel ( dff_estructura, 934 )
engineSetModelLODDistance(934, 500)
